services:
  frontend:
    image: akbackup/quirknotes_frontend:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile_frontend
    ports:
    - "3000:80"
    environment:
    - ENV=Docker

  backend:
    image: akbackup/quirknotes_backend:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile_backend
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"